# Generated by Django 2.0.7 on 2018-07-26 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField(blank=True, max_length=256)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('modified_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('IMPORTANT', 'Urgent and important'), ('NOT_URGENT', 'Important, not urgent'), ('NOT_IMPORTANT', 'Urgent, not important'), ('TRIVIA', 'Not urgent, not important')], default='TRIVIA', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='todo.Tag')),
            ],
        ),
    ]
