# Generated by Django 2.0.7 on 2018-08-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180803_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='order',
            new_name='priority',
        ),
    ]
